# Generated by Django 4.0.5 on 2022-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(default='', max_length=12, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('blood', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=0)),
                ('department', models.CharField(default='', max_length=30)),
                ('attendance', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('prescripted_date', models.DateField(auto_now=True)),
                ('outstanding', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
