# Generated by Django 4.0.5 on 2022-06-27 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DOCTOR', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
        ('PATIENT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription2',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.appointment'),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='docter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCTOR.docter'),
        ),
        migrations.AddField(
            model_name='prescription2',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient'),
        ),
        migrations.AddField(
            model_name='docter',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
